name: Run Jest testing suite
on:
  workflow_dispatch:
  pull_request:

env:
  NODE_ENV: "test"

jobs:
  testing:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Jest With Coverage
        run: bun install --immutable --immutable-cache --check-cache && bun run test

      - name: Add Jest Report to Summary
        if: always()
        run: echo "$(cat test-dashboard.md)" >> $GITHUB_STEP_SUMMARY
