name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
      - uses: actions/checkout@v4
      - name: Set up bun
        uses: oven-sh/setup-bun@v2
      - run: |
          bun install --immutable --immutable-cache --check-cache
